gateways:
  bigquery:
    connection:
      type: bigquery
      project: "${BIGQUERY_PROJECT}"
    state_connection:
      type: postgres
      host: "${POSTGRES_HOST}"
      port: 5432
      user: "${POSTGRES_USER:-postgres}"
      password: "${POSTGRES_PASSWORD}"
      database: "${POSTGRES_DATABASE:-postgres}"

  local:
    connection:
      type: duckdb
      database: dev.duckdb

default_gateway: local
disable_anonymized_analytics: true

model_defaults:
  dialect: bigquery
  start: 2025-07-01
  cron: "@daily"

linter:
  enabled: false
